# Site settings
title: Geohackweek
email: arendta@uw.edu
url: https://geohackweek.github.io
description: "A workshop and hackathon in geospatial data science at the University of Washington eScience Institute"
encoding: UTF-8

# Google services
google_analytics: UA—77504214-2

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#444444'
  links: '#e8e3d3'

# Footer settings
footer: Arendt, Anthony UW eScience Institute

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/search?q=%23geohackweek&src=typd
  #- title: facebook
  #  url:
  #- title: stack-overflow
  #  url: http://stackoverflow.com/questions/tagged/jekyll
  #- title: bitbucket
  #  url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/geohackweek

# Build settings
markdown: kramdown
permalink: pretty
