# Welcome to Jekyll!
#

# Site settings
title: Strefa Gier
description: |
  Strona polskiej społeczności gamingowej  
  Streafa Gier
owner: Strefa Gier # or company name
first_published: 1996 # if migrating another site, the year of your first publish
email: streafgiercompl@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://flieswithwind.github.io" # the base hostname & protocol for your site
social:
  # twitter: https://twitter.com/<username>
  # github: https://github.com/<username>
  # linkedin-square: https://linkedin.com/in/<username>
  # facebook-official: https://facebook.com/<username>
  # google-plus-square: https://plus.google.com/u/0/+<username>
  discord: https://discord.gg/UyVAHJtXPA
  steam: https://steamcommunity.com/groups/sg-grupa
  facebook: https://www.facebook.com/people/Strefa-Gier/100066493794051
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
